### ISSUE TITLE
Bad gateway 502 error

### ISSUE THREAD

**Issue by mkao006** [mkao006/random_walker#141]
The error message from `sudo docker-compose logs` is shown below.

web_1   | 2016-07-15 06:25:53 UTC [13-4] LOG:  record with zero length at 0/1DB6D88
web_1   | 2016-07-15 06:25:53 UTC [13-5] LOG:  redo done at 0/1DB6D58
web_1   | 2016-07-15 06:25:53 UTC [13-6] LOG:  last completed transaction was at log time 2016-07-11 01:08:00.502227+00
web_1   | Traceback (most recent call last):
web_1   |   File "manage.py", line 10, in <module>
web_1   |     execute_from_command_line(sys.argv)
web_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
web_1   |     utility.execute()
web_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 302, in execute
web_1   |     settings.INSTALLED_APPS
web_1   |   File "/usr/local/lib/python2.7/dist-packages/django/conf/**init**.py", line 55, in **getattr**
web_1   |     self._setup(name)
web_1   |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
web_1   |     self._wrapped = Settings(settings_module)
web_1   |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in **init**
web_1   |     mod = importlib.import_module(self.SETTINGS_MODULE)
web_1   |   File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
web_1   |     **import**(name)
web_1   | ImportError: No module named local_docker_single
web_1   | mv: cannot stat 'random_walker.ini': No such file or directory
web_1   | mv: cannot stat 'uwsgi.conf': No such file or directory

**Comment by mkao006** [comment]
Fixed incorrect reference to the wrong settings file in 379ba979cb94124e64a5bf298f4405a2e89faf65, but the configuration file error still exist.

**Comment by mkao006** [comment]
The configuration error only exist because the container is restarted when it fails. However, since it was already moved in the first run, thus the file no longer exist. Need to investigate the source of the error that caused the first run to fail.

**Comment by mkao006** [comment]
The source of the error was because there was no port to connect to after we have removed the unix socket. Now we have reconfigured and add the port 8000 at 5358423d244f70f0ebe495c7514d9fcb683076d9

**Comment by mkao006** [comment]
Another source of the error was from the use of Nginx configuration copied from a github repo which was not suitable for our app. Reverting to the same Nginx configuration  used in the single docker container, the error was resolved.

Resolved at f9490e3e61d7bc84f78475d17314d36f3faad041
